### ISSUE TITLE
Units stack on very large screens

### ISSUE THREAD

**Issue by matthewpeixoto** [algonquindesign-grads/2018-coming-soon#5]
On very large displays the event units stack on top of each other instead of remaining side-by-side.
  
![screen shot 2018-01-25 at 2 13 43 pm](https://user-images.githubusercontent.com/16690200/35407479-18d4ea58-01da-11e8-8505-4338d848117a.png)

**Comment by kaylaobritsch** [comment]
Stacking is caused by

.next-event,
.main-event {
  min-width: 30vw;
  padding: 2em 2em 0 2em;
}

Is this on there for a reason?

**Comment by matthewpeixoto** [comment]
I don't see a need for a min-width—feel free to clean up some code.
