### ISSUE TITLE
Logo is cut off on mobile (Samsung galaxy S7, Chrome 63.0.3239.111)

### ISSUE THREAD

**Issue by matthewpeixoto** [algonquindesign-grads/2018-coming-soon#9]
Someone noticed that the logo is cutoff on their Samsung galaxy S7 using Chrome.

![20180125_170047](https://user-images.githubusercontent.com/16690200/35415966-706d1fa4-01f5-11e8-841a-f3dd1f8a1ea8.png)

**Comment by kaylaobritsch** [comment]
Pixel 2, chrome. Mines not initially cut off but when I scroll down... the frame does something weird.

**Comment by kaylaobritsch** [comment]
![screenshot_20180125-174632](https://user-images.githubusercontent.com/16653288/35416805-97bdfb52-01f8-11e8-84dc-3a66055ba693.png)
